"""PDF rendering (reportlab) for the approved quote and the export documents."""
from __future__ import annotations

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

_ss = getSampleStyleSheet()
H1 = ParagraphStyle("h1", parent=_ss["Heading1"], fontSize=16, spaceAfter=4)
SMALL = ParagraphStyle("small", parent=_ss["BodyText"], fontSize=8, textColor=colors.HexColor("#555555"))
BODY = ParagraphStyle("body", parent=_ss["BodyText"], fontSize=9.5, leading=13)
SYNTHETIC = "SYNTHETIC DEMO DOCUMENT - generated by an independent prototype with fictional data. Not a real trade document."


def _build(story: list) -> bytes:
    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                      bottomMargin=16 * mm, title="OpsPilot document").build(story)
    return buf.getvalue()


def _table(rows: list[list[Any]], widths: list[float] | None = None, header: bool = True) -> Table:
    t = Table(rows, colWidths=widths, hAlign="LEFT")
    style = [("FONTSIZE", (0, 0), (-1, -1), 9), ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bbbbbb")),
             ("VALIGN", (0, 0), (-1, -1), "TOP"), ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]
    if header:
        style += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef1f5")), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
    t.setStyle(TableStyle(style))
    return t


def _kv(pairs: list[tuple[str, Any]]) -> Table:
    t = _table([[k, "" if v is None else str(v)] for k, v in pairs], [55 * mm, 115 * mm], header=False)
    t.setStyle(TableStyle([("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold")]))
    return t


def quote_pdf(run_id: str, customer: str | None, breakdown: dict, approver: str, decided_at: str) -> bytes:
    b = breakdown
    story: list = [Paragraph("Quotation", H1), Paragraph(SYNTHETIC, SMALL), Spacer(1, 6),
                   _kv([("Reference", run_id), ("Customer", customer or "-"),
                        ("Product", f"{b['product_name']} ({b['product_code']})"),
                        ("Quantity", f"{b['qty_kg']:g} kg"), ("Minimum purity", f"{b['purity_min']:g} %"),
                        ("Incoterm", b["incoterm"] + (f" {b['destination_port']}" if b.get("destination_port") and b["incoterm"] == "CIF" else "")),
                        ("Unit price", f"{b['price_per_kg']} {b['currency']} / kg"),
                        ("Total", f"{b['total']} {b['currency']}"), ("Valid until", b["quote_valid_until"]),
                        ("Approved by", f"{approver} on {decided_at}")]), Spacer(1, 10),
                   Paragraph("Cost breakdown (internal reference)", BODY)]
    rows = [["Item", "Basis", "Amount (USD)"]] + [[l["label"], l["formula"], l["amount"]] for l in b["lines"]]
    rows.append(["Landed cost", "", b["landed_cost"]])
    rows.append(["Margin", f"{float(b['margin_pct']) * 100:.1f} % of selling price", ""])
    rows.append(["Total", "", b["total"]])
    story.append(_table(rows, [48 * mm, 90 * mm, 32 * mm]))
    return _build(story)


def _party(d: dict | None) -> str:
    return "-" if not d else f"{d.get('name', '')}"


def export_pdf(doc: dict) -> bytes:
    t = doc["doc_type"]
    title = {"commercial_invoice": "Commercial Invoice", "packing_list": "Packing List",
             "certificate_of_origin": "Certificate of Origin", "shipping_instruction": "Shipping Instruction"}[t]
    p = doc.get("product", {})
    pairs: list[tuple[str, Any]] = []
    if t == "commercial_invoice":
        pairs = [("Invoice no.", doc["invoice_no"]), ("Date", doc["date"]), ("Seller", _party(doc["seller"])),
                 ("Consignee", _party(doc["consignee"])), ("Product", f"{p.get('name')} ({p.get('code')})"),
                 ("HS code", p.get("hs_code")), ("Net quantity", f"{doc['net_quantity_kg']:g} kg"),
                 ("Unit price", f"{doc['unit_price_per_kg']} {doc['currency']} / kg"),
                 ("Total value", f"{doc['total_value']} {doc['currency']}"), ("Incoterm", doc["incoterm"]),
                 ("Country of origin", doc["origin_country"]), ("Destination port", doc["destination_port"])]
    elif t == "packing_list":
        pairs = [("Packing list no.", doc["packing_list_no"]), ("Invoice no.", doc["invoice_no"]),
                 ("Consignee", _party(doc["consignee"])), ("Product", f"{p.get('name')} ({p.get('code')})"),
                 ("HS code", p.get("hs_code")), ("Net quantity", f"{doc['net_quantity_kg']:g} kg"),
                 ("Gross weight", f"{doc['gross_weight_kg']:g} kg"), ("Packaging", doc["package_type"]),
                 ("Number of packages", doc["packages_count"]),
                 ("Net weight / package", f"{doc['net_weight_per_package_kg']:g} kg"),
                 ("Country of origin", doc["origin_country"]), ("Destination port", doc["destination_port"])]
    elif t == "certificate_of_origin":
        pairs = [("Certificate no.", doc["coo_no"]), ("Consignee", _party(doc["consignee"])),
                 ("Product", f"{p.get('name')} ({p.get('code')})"), ("HS code", p.get("hs_code")),
                 ("Net quantity", f"{doc['net_quantity_kg']:g} kg"), ("Country of origin", doc["origin_country"]),
                 ("Destination country", doc.get("destination_country"))]
    else:
        pairs = [("SI no.", doc["si_no"]), ("Shipper", _party(doc["shipper"])), ("Consignee", _party(doc["consignee"])),
                 ("Product", f"{p.get('name')} ({p.get('code')})"), ("HS code", p.get("hs_code")),
                 ("Net quantity", f"{doc['net_quantity_kg']:g} kg"), ("Gross weight", f"{doc['gross_weight_kg']:g} kg"),
                 ("Packages", doc["packages_count"]), ("Port of loading", doc["port_of_loading"]),
                 ("Destination port", doc["destination_port"]), ("Incoterm", doc["incoterm"]),
                 ("Hazmat class", doc.get("hazmat_class") or "None")]
    return _build([Paragraph(title, H1), Paragraph(SYNTHETIC, SMALL), Spacer(1, 8), _kv(pairs)])
